### ISSUE TITLE
Lib::debug: flooding debug.log & settings page

### ISSUE THREAD

**Issue by splaquet** [ddur/Warp-iMagick#13]
Is there a way to disable the Lib::debug: messages generated by the plugin? Considering that other plugins are being referenced by this plugin, it's REALLY generating a lot of unnecessary lines in the log.  

The alerts are (and have been) flooding my debug.log, as well as the top of the plugin's Settings page.

'Lib::debug: Metadata update WITHIN "wp_create_image_subsizes" scope - $attachment_id: 10648
Lib::debug: Attachment (10648) metadata change detected
Lib::debug: Save metadata backup - $attachment_id: 10648
Lib::debug: Regenerate wp_create_image_subsizes( $file, _ ) does match [file] or [original_image]
Lib::debug: Post mime-type is not equal to JPEG or PNG image type:image/webp.
Lib::debug: Metadata update WITHIN "wp_create_image_subsizes" scope - $attachment_id: 10648
Lib::debug: Skip metadata backup [no-overwrite] - $attachment_id: 10648
Lib::debug: Metadata update WITHIN "wp_create_image_subsizes" scope - $attachment_id: 10648
Lib::debug: Skip metadata backup [no-overwrite] - $attachment_id: 10648
Lib::debug: Fixing $metadata sizes in context of: create
Lib::debug: Metadata update OUT-OF "wp_create_image_subsizes" scope - $attachment_id: 10648
Lib::debug: (Client) $remote_host: domain.local
Lib::debug: (Client) $uplink_host: warp-imagick.pagespeed.club
Lib::debug: (Client) $_local_host: domain.local
Lib::debug: (Client) Remote host ignored.'

<img width="939" alt="image" src="https://github.com/ddur/Warp-iMagick/assets/6146508/d3c266f5-36f9-420b-b5ba-7be45cfcb8c4">

**Comment by ddur** [comment]
Sure: Set WP_DEBUG to false.

Since recently I use [WP_DEBUG Toggle](https://wordpress.org/plugins/enable-wp-debug-toggle/).

**Comment by ddur** [comment]
@splaquet 

If you do not debug Warp iMagick, disable it.

Anyways, next version I'm just working on, already has an option to disable most/too frequent debug messages.

**Comment by splaquet** [comment]
thanks for the quick response!

I am using and do appreciate your efforts & plugin!  I don't see any reasons on why we'd disable it, since we're taking advantage of its offerings.

the problem is that we're in a /development environment and we always have the debug.log rolling in the background.  typically we keep an eye on new items, as they pop up.  it's a bit distracting when everything flows through.

I use this snippet in my wp-config.php:
`//define( 'WP_DEBUG', false );
define( 'WP_DEBUG', true ); // Or false
if ( WP_DEBUG ) {
  define( 'WP_DEBUG_LOG', true );
  define( 'WP_DEBUG_DISPLAY', false );
//  @ini_set( 'display_errors', 0 );
//  define('WP_DISABLE_FATAL_ERROR_HANDLER', true);

  $GLOBALS['wp_filter'] = [
    'enable_wp_debug_mode_checks' => [
      10 => [[
        'accepted_args' => 0,
        'function'      => function() { return false; },
      ]],
    ],
  ];

  error_reporting(E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED);
//  define( 'SCRIPT_DEBUG', true );
//  define( 'SAVEQUERIES', true );
}`
