### ISSUE TITLE
Wordpress Dashboard reporting "Warp iMagick: New version is available. Please upgrade to version 1.11."

### ISSUE THREAD

**Issue by iCounsellorUK** [ddur/Warp-iMagick#14]
... however, the version on here from 6 months ago, and the version downloaded from https://warp-imagick.pagespeed.club/ has README stating "Stable tag: 1.10.4.1"

Where is this mysterious version 1,11, please? Or is a system, somewhere, telling fibs ;)

Cheers,
iCounsellor

**Comment by ddur** [comment]
Version 1.11 is available via updates.
Message appears if WordPress auto-update is disabled for warp-imagick plugin.

Either enable WordPress auto-update for warp-imagick plugin or upgrade manually:
Go to "Menu"->"Plugins" or "Menu"->"Dashboard"->"Updates" and upgrade manually.

Cheers.

**Comment by ddur** [comment]
@iCounsellorUK 

Please close issue or respond after you read the answer. Thanks.

**Comment by iCounsellorUK** [comment]
I'm sorry, I should have been more clear.

Despite the notification that a new version (1.11) is available, neither the "Dashboard/Updates" nor "Plugins/Update Available" pages show that Warp iMagick has a new version available to download. There's nothing to click to do the upgrade.

My site IS registered for automatic updates.
![warpmagic updates](https://github.com/ddur/Warp-iMagick/assets/18662069/13ea23a2-57d2-4a36-868c-7c625c27d992)

I can find no-where an action to upgrade manually; the automatic update appears not to be working.

The version I have installed is 1.10.4.1 and the version downloaded manually from your update website (https://warp-imagick.pagespeed.club/ ) is 1.10.4.1 (README file - confirmed again just now)

FWIW my Wordpress installation is  6.4.2 (multisite). The plugin is activated on a subsite (with automatic-updates enabled/subscribed on https://warp-imagick.pagespeed.club/)

How may assist you further?

**Comment by iCounsellorUK** [comment]
OK - found a "workaround".

Because I use Wordpress Multisite, I activate the plugin on any subsites that use the plugin (so the main host-site does have the plugin activated).

Subsites would report that an upgrade was available, but would offer no link to execure the upgrade. Wordpress Multisite Dashboard would also not show that an upgrade was available.

To work around this, one has to activate the plugin on the main host site (and subscribe the domain name to your service). In this way, the main site executes the upgrade on behalf of all subsites.

Messy, but it works.

Hope this is useful to you working with Multisite installations.

**Comment by ddur** [comment]
@iCounsellorUK 

Thank You!

**Comment by ddur** [comment]
@iCounsellorUK 

Sorry, I didn't know you are using wp-multisite instalation.

Because this Plugin Updates are not available from WordPress Update server, warp-imagick plugin has to provide its own Update Checker & Server. So, custom Update Checker is integral part of warp-imagick plugin.

As far I can conclude from your info, on wp-multisite installation, plugins are updated only on main-site. So, if plugin is not activated on main-site, warp-imagick Plugin Update Checker code is never loaded.

On single wp-site instalation, circumstances are about the same: If plugin is not activated, warp-imagick Plugin Update Checker code is never loaded.
