### ISSUE TITLE
plugin notice: tested up to WP 6.4 (Now 6.6.1). Please update.

### ISSUE THREAD

**Issue by splaquet** [ddur/Warp-iMagick#16]
subject says it all

**This version of plugin is tested up to WP 6.4 (Now 6.6.1). Please update.**

<img width="510" alt="image" src="https://github.com/user-attachments/assets/3b5c1bc8-8603-4741-89f0-12a6311d121e">

**Comment by ddur** [comment]
Thank you for reminding me. :sunglasses: 

Anyways, that is only message, if plugin still works without issues, just keep using it.
