### ISSUE TITLE
1.11?

### ISSUE THREAD

**Issue by ozgurkazancci** [ddur/Warp-iMagick#17]
Hello and thanks for this plugin. I've been using it since years. Today I installed the latest zip file and registered for automated updates, for a website of mine.

I then received a notification on Wordpress dashboard in Plugins section, telling there is a new version of the plugin which is version 1.11 now.

However, this repository (here on Github) does not has anything related to 1.11, latest version seems 1.10.4.1 here.

What does 1.11 has and where is the list of changes and why they are not here on Github? Any explanation?

Thank you.

**Comment by ddur** [comment]
> Hello and thanks for this plugin. I've been using it since years. Today I installed the latest zip file and registered for automated updates, for a website of mine.
> 
> I then received a notification on Wordpress dashboard in Plugins section, telling there is a new version of the plugin which is version 1.11 now.
> 
> However, this repository (here on Github) does not has anything related to 1.11, latest version seems 1.10.4.1 here.
> 
The repository on Github contains last version to be updated.

> What does 1.11 has and where is the list of changes and why they are not here on Github? Any explanation?
> 
To see the changes, click on notification link [View version 1.11 details]()

![image](https://github.com/user-attachments/assets/a89c805a-2334-4597-8353-c81e395003a3)
